/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValituksetRouteImport } from './routes/valitukset'
import { Route as UutisetRouteImport } from './routes/uutiset'
import { Route as ToimitusRouteImport } from './routes/toimitus'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PikakasinotRouteImport } from './routes/pikakasinot'
import { Route as MaksutavatRouteImport } from './routes/maksutavat'
import { Route as LisenssitRouteImport } from './routes/lisenssit'
import { Route as KotiutusnopeusRouteImport } from './routes/kotiutusnopeus'
import { Route as KolikkopelitRouteImport } from './routes/kolikkopelit'
import { Route as KirjoittajatRouteImport } from './routes/kirjoittajat'
import { Route as KasinotRouteImport } from './routes/kasinot'
import { Route as BonuksetRouteImport } from './routes/bonukset'
import { Route as BlogiRouteImport } from './routes/blogi'
import { Route as ArvostelutRouteImport } from './routes/arvostelut'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UutisetUudetKasinotRouteImport } from './routes/uutiset.uudet-kasinot'
import { Route as MaksutavatSlugRouteImport } from './routes/maksutavat.$slug'
import { Route as KasinotSlugRouteImport } from './routes/kasinot.$slug'
import { Route as BlogiSlugRouteImport } from './routes/blogi.$slug'
import { Route as ArvostelutSlugRouteImport } from './routes/arvostelut.$slug'

const ValituksetRoute = ValituksetRouteImport.update({
  id: '/valitukset',
  path: '/valitukset',
  getParentRoute: () => rootRouteImport,
} as any)
const UutisetRoute = UutisetRouteImport.update({
  id: '/uutiset',
  path: '/uutiset',
  getParentRoute: () => rootRouteImport,
} as any)
const ToimitusRoute = ToimitusRouteImport.update({
  id: '/toimitus',
  path: '/toimitus',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PikakasinotRoute = PikakasinotRouteImport.update({
  id: '/pikakasinot',
  path: '/pikakasinot',
  getParentRoute: () => rootRouteImport,
} as any)
const MaksutavatRoute = MaksutavatRouteImport.update({
  id: '/maksutavat',
  path: '/maksutavat',
  getParentRoute: () => rootRouteImport,
} as any)
const LisenssitRoute = LisenssitRouteImport.update({
  id: '/lisenssit',
  path: '/lisenssit',
  getParentRoute: () => rootRouteImport,
} as any)
const KotiutusnopeusRoute = KotiutusnopeusRouteImport.update({
  id: '/kotiutusnopeus',
  path: '/kotiutusnopeus',
  getParentRoute: () => rootRouteImport,
} as any)
const KolikkopelitRoute = KolikkopelitRouteImport.update({
  id: '/kolikkopelit',
  path: '/kolikkopelit',
  getParentRoute: () => rootRouteImport,
} as any)
const KirjoittajatRoute = KirjoittajatRouteImport.update({
  id: '/kirjoittajat',
  path: '/kirjoittajat',
  getParentRoute: () => rootRouteImport,
} as any)
const KasinotRoute = KasinotRouteImport.update({
  id: '/kasinot',
  path: '/kasinot',
  getParentRoute: () => rootRouteImport,
} as any)
const BonuksetRoute = BonuksetRouteImport.update({
  id: '/bonukset',
  path: '/bonukset',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogiRoute = BlogiRouteImport.update({
  id: '/blogi',
  path: '/blogi',
  getParentRoute: () => rootRouteImport,
} as any)
const ArvostelutRoute = ArvostelutRouteImport.update({
  id: '/arvostelut',
  path: '/arvostelut',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UutisetUudetKasinotRoute = UutisetUudetKasinotRouteImport.update({
  id: '/uudet-kasinot',
  path: '/uudet-kasinot',
  getParentRoute: () => UutisetRoute,
} as any)
const MaksutavatSlugRoute = MaksutavatSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MaksutavatRoute,
} as any)
const KasinotSlugRoute = KasinotSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KasinotRoute,
} as any)
const BlogiSlugRoute = BlogiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogiRoute,
} as any)
const ArvostelutSlugRoute = ArvostelutSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArvostelutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arvostelut': typeof ArvostelutRouteWithChildren
  '/blogi': typeof BlogiRouteWithChildren
  '/bonukset': typeof BonuksetRoute
  '/kasinot': typeof KasinotRouteWithChildren
  '/kirjoittajat': typeof KirjoittajatRoute
  '/kolikkopelit': typeof KolikkopelitRoute
  '/kotiutusnopeus': typeof KotiutusnopeusRoute
  '/lisenssit': typeof LisenssitRoute
  '/maksutavat': typeof MaksutavatRouteWithChildren
  '/pikakasinot': typeof PikakasinotRoute
  '/reset-password': typeof ResetPasswordRoute
  '/toimitus': typeof ToimitusRoute
  '/uutiset': typeof UutisetRouteWithChildren
  '/valitukset': typeof ValituksetRoute
  '/arvostelut/$slug': typeof ArvostelutSlugRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/kasinot/$slug': typeof KasinotSlugRoute
  '/maksutavat/$slug': typeof MaksutavatSlugRoute
  '/uutiset/uudet-kasinot': typeof UutisetUudetKasinotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arvostelut': typeof ArvostelutRouteWithChildren
  '/blogi': typeof BlogiRouteWithChildren
  '/bonukset': typeof BonuksetRoute
  '/kasinot': typeof KasinotRouteWithChildren
  '/kirjoittajat': typeof KirjoittajatRoute
  '/kolikkopelit': typeof KolikkopelitRoute
  '/kotiutusnopeus': typeof KotiutusnopeusRoute
  '/lisenssit': typeof LisenssitRoute
  '/maksutavat': typeof MaksutavatRouteWithChildren
  '/pikakasinot': typeof PikakasinotRoute
  '/reset-password': typeof ResetPasswordRoute
  '/toimitus': typeof ToimitusRoute
  '/uutiset': typeof UutisetRouteWithChildren
  '/valitukset': typeof ValituksetRoute
  '/arvostelut/$slug': typeof ArvostelutSlugRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/kasinot/$slug': typeof KasinotSlugRoute
  '/maksutavat/$slug': typeof MaksutavatSlugRoute
  '/uutiset/uudet-kasinot': typeof UutisetUudetKasinotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arvostelut': typeof ArvostelutRouteWithChildren
  '/blogi': typeof BlogiRouteWithChildren
  '/bonukset': typeof BonuksetRoute
  '/kasinot': typeof KasinotRouteWithChildren
  '/kirjoittajat': typeof KirjoittajatRoute
  '/kolikkopelit': typeof KolikkopelitRoute
  '/kotiutusnopeus': typeof KotiutusnopeusRoute
  '/lisenssit': typeof LisenssitRoute
  '/maksutavat': typeof MaksutavatRouteWithChildren
  '/pikakasinot': typeof PikakasinotRoute
  '/reset-password': typeof ResetPasswordRoute
  '/toimitus': typeof ToimitusRoute
  '/uutiset': typeof UutisetRouteWithChildren
  '/valitukset': typeof ValituksetRoute
  '/arvostelut/$slug': typeof ArvostelutSlugRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/kasinot/$slug': typeof KasinotSlugRoute
  '/maksutavat/$slug': typeof MaksutavatSlugRoute
  '/uutiset/uudet-kasinot': typeof UutisetUudetKasinotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arvostelut'
    | '/blogi'
    | '/bonukset'
    | '/kasinot'
    | '/kirjoittajat'
    | '/kolikkopelit'
    | '/kotiutusnopeus'
    | '/lisenssit'
    | '/maksutavat'
    | '/pikakasinot'
    | '/reset-password'
    | '/toimitus'
    | '/uutiset'
    | '/valitukset'
    | '/arvostelut/$slug'
    | '/blogi/$slug'
    | '/kasinot/$slug'
    | '/maksutavat/$slug'
    | '/uutiset/uudet-kasinot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arvostelut'
    | '/blogi'
    | '/bonukset'
    | '/kasinot'
    | '/kirjoittajat'
    | '/kolikkopelit'
    | '/kotiutusnopeus'
    | '/lisenssit'
    | '/maksutavat'
    | '/pikakasinot'
    | '/reset-password'
    | '/toimitus'
    | '/uutiset'
    | '/valitukset'
    | '/arvostelut/$slug'
    | '/blogi/$slug'
    | '/kasinot/$slug'
    | '/maksutavat/$slug'
    | '/uutiset/uudet-kasinot'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arvostelut'
    | '/blogi'
    | '/bonukset'
    | '/kasinot'
    | '/kirjoittajat'
    | '/kolikkopelit'
    | '/kotiutusnopeus'
    | '/lisenssit'
    | '/maksutavat'
    | '/pikakasinot'
    | '/reset-password'
    | '/toimitus'
    | '/uutiset'
    | '/valitukset'
    | '/arvostelut/$slug'
    | '/blogi/$slug'
    | '/kasinot/$slug'
    | '/maksutavat/$slug'
    | '/uutiset/uudet-kasinot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArvostelutRoute: typeof ArvostelutRouteWithChildren
  BlogiRoute: typeof BlogiRouteWithChildren
  BonuksetRoute: typeof BonuksetRoute
  KasinotRoute: typeof KasinotRouteWithChildren
  KirjoittajatRoute: typeof KirjoittajatRoute
  KolikkopelitRoute: typeof KolikkopelitRoute
  KotiutusnopeusRoute: typeof KotiutusnopeusRoute
  LisenssitRoute: typeof LisenssitRoute
  MaksutavatRoute: typeof MaksutavatRouteWithChildren
  PikakasinotRoute: typeof PikakasinotRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ToimitusRoute: typeof ToimitusRoute
  UutisetRoute: typeof UutisetRouteWithChildren
  ValituksetRoute: typeof ValituksetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valitukset': {
      id: '/valitukset'
      path: '/valitukset'
      fullPath: '/valitukset'
      preLoaderRoute: typeof ValituksetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uutiset': {
      id: '/uutiset'
      path: '/uutiset'
      fullPath: '/uutiset'
      preLoaderRoute: typeof UutisetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toimitus': {
      id: '/toimitus'
      path: '/toimitus'
      fullPath: '/toimitus'
      preLoaderRoute: typeof ToimitusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pikakasinot': {
      id: '/pikakasinot'
      path: '/pikakasinot'
      fullPath: '/pikakasinot'
      preLoaderRoute: typeof PikakasinotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maksutavat': {
      id: '/maksutavat'
      path: '/maksutavat'
      fullPath: '/maksutavat'
      preLoaderRoute: typeof MaksutavatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lisenssit': {
      id: '/lisenssit'
      path: '/lisenssit'
      fullPath: '/lisenssit'
      preLoaderRoute: typeof LisenssitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotiutusnopeus': {
      id: '/kotiutusnopeus'
      path: '/kotiutusnopeus'
      fullPath: '/kotiutusnopeus'
      preLoaderRoute: typeof KotiutusnopeusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kolikkopelit': {
      id: '/kolikkopelit'
      path: '/kolikkopelit'
      fullPath: '/kolikkopelit'
      preLoaderRoute: typeof KolikkopelitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kirjoittajat': {
      id: '/kirjoittajat'
      path: '/kirjoittajat'
      fullPath: '/kirjoittajat'
      preLoaderRoute: typeof KirjoittajatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasinot': {
      id: '/kasinot'
      path: '/kasinot'
      fullPath: '/kasinot'
      preLoaderRoute: typeof KasinotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonukset': {
      id: '/bonukset'
      path: '/bonukset'
      fullPath: '/bonukset'
      preLoaderRoute: typeof BonuksetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogi': {
      id: '/blogi'
      path: '/blogi'
      fullPath: '/blogi'
      preLoaderRoute: typeof BlogiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arvostelut': {
      id: '/arvostelut'
      path: '/arvostelut'
      fullPath: '/arvostelut'
      preLoaderRoute: typeof ArvostelutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uutiset/uudet-kasinot': {
      id: '/uutiset/uudet-kasinot'
      path: '/uudet-kasinot'
      fullPath: '/uutiset/uudet-kasinot'
      preLoaderRoute: typeof UutisetUudetKasinotRouteImport
      parentRoute: typeof UutisetRoute
    }
    '/maksutavat/$slug': {
      id: '/maksutavat/$slug'
      path: '/$slug'
      fullPath: '/maksutavat/$slug'
      preLoaderRoute: typeof MaksutavatSlugRouteImport
      parentRoute: typeof MaksutavatRoute
    }
    '/kasinot/$slug': {
      id: '/kasinot/$slug'
      path: '/$slug'
      fullPath: '/kasinot/$slug'
      preLoaderRoute: typeof KasinotSlugRouteImport
      parentRoute: typeof KasinotRoute
    }
    '/blogi/$slug': {
      id: '/blogi/$slug'
      path: '/$slug'
      fullPath: '/blogi/$slug'
      preLoaderRoute: typeof BlogiSlugRouteImport
      parentRoute: typeof BlogiRoute
    }
    '/arvostelut/$slug': {
      id: '/arvostelut/$slug'
      path: '/$slug'
      fullPath: '/arvostelut/$slug'
      preLoaderRoute: typeof ArvostelutSlugRouteImport
      parentRoute: typeof ArvostelutRoute
    }
  }
}

interface ArvostelutRouteChildren {
  ArvostelutSlugRoute: typeof ArvostelutSlugRoute
}

const ArvostelutRouteChildren: ArvostelutRouteChildren = {
  ArvostelutSlugRoute: ArvostelutSlugRoute,
}

const ArvostelutRouteWithChildren = ArvostelutRoute._addFileChildren(
  ArvostelutRouteChildren,
)

interface BlogiRouteChildren {
  BlogiSlugRoute: typeof BlogiSlugRoute
}

const BlogiRouteChildren: BlogiRouteChildren = {
  BlogiSlugRoute: BlogiSlugRoute,
}

const BlogiRouteWithChildren = BlogiRoute._addFileChildren(BlogiRouteChildren)

interface KasinotRouteChildren {
  KasinotSlugRoute: typeof KasinotSlugRoute
}

const KasinotRouteChildren: KasinotRouteChildren = {
  KasinotSlugRoute: KasinotSlugRoute,
}

const KasinotRouteWithChildren =
  KasinotRoute._addFileChildren(KasinotRouteChildren)

interface MaksutavatRouteChildren {
  MaksutavatSlugRoute: typeof MaksutavatSlugRoute
}

const MaksutavatRouteChildren: MaksutavatRouteChildren = {
  MaksutavatSlugRoute: MaksutavatSlugRoute,
}

const MaksutavatRouteWithChildren = MaksutavatRoute._addFileChildren(
  MaksutavatRouteChildren,
)

interface UutisetRouteChildren {
  UutisetUudetKasinotRoute: typeof UutisetUudetKasinotRoute
}

const UutisetRouteChildren: UutisetRouteChildren = {
  UutisetUudetKasinotRoute: UutisetUudetKasinotRoute,
}

const UutisetRouteWithChildren =
  UutisetRoute._addFileChildren(UutisetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArvostelutRoute: ArvostelutRouteWithChildren,
  BlogiRoute: BlogiRouteWithChildren,
  BonuksetRoute: BonuksetRoute,
  KasinotRoute: KasinotRouteWithChildren,
  KirjoittajatRoute: KirjoittajatRoute,
  KolikkopelitRoute: KolikkopelitRoute,
  KotiutusnopeusRoute: KotiutusnopeusRoute,
  LisenssitRoute: LisenssitRoute,
  MaksutavatRoute: MaksutavatRouteWithChildren,
  PikakasinotRoute: PikakasinotRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ToimitusRoute: ToimitusRoute,
  UutisetRoute: UutisetRouteWithChildren,
  ValituksetRoute: ValituksetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
